/version 1.10.0-alpha.1

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -54,7 +54,12 @@ jobs:
       - name: Install with pip
         run: |
           python -m pip install --upgrade pip
-          pip install --user --force podaac-data-subscriber==${{ needs.release.outputs.publishedVersion }}
+          
+          # Retry 3 times before the steps actually fails because sometimes it takes a minute for pip to recognize the new version
+          (echo "pip Install Attempt: 1" && pip install --user --force podaac-data-subscriber==${{ needs.release.outputs.publishedVersion }}) || \
+          (echo "pip Install Attempt: 2" && pip install --user --force podaac-data-subscriber==${{ needs.release.outputs.publishedVersion }}) || \
+          (echo "pip Install Attempt: 3" && pip install --user --force podaac-data-subscriber==${{ needs.release.outputs.publishedVersion }}) || \
+          (echo "pip Install Step Failed" && exit 1)
       - name: Print Subscriber Usage
         run: |
           podaac-data-subscriber -h
